name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Set up Go
        uses: actions/setup-go@main
        with:
          go-version: "1.23"
          check-latest: true

      - name: Build
        run: |
          GOOS=linux GOARCH=amd64 go build -o r2sync-linux-amd64 ./cmd/r2sync
          GOOS=linux GOARCH=arm64 go build -o r2sync-linux-arm64 ./cmd/r2sync
          GOOS=darwin GOARCH=amd64 go build -o r2sync-darwin-amd64 ./cmd/r2sync
          GOOS=darwin GOARCH=arm64 go build -o r2sync-darwin-arm64 ./cmd/r2sync
          GOOS=windows GOARCH=amd64 go build -o r2sync-windows-amd64.exe ./cmd/r2sync

      - name: Create Release
        uses: softprops/action-gh-release@master
        with:
          files: |
            r2sync-linux-amd64
            r2sync-linux-arm64
            r2sync-darwin-amd64
            r2sync-darwin-arm64
            r2sync-windows-amd64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
